name: Check Javascript Vulnerabilities.
description: "Check javascript vulnerabilities to the PR"

inputs:
  files:
    description: "List of file paths to check"
    required: true
  working_directory: 
    description: "A working directory passed from the caller workflow"
    required: true
  node_version:
    description: "The version of nodejs to use, defaults to `14`."
    default: "14"
    required: false


runs:
  using: "composite"
  steps:
    - name: Install Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node_version }}

     - name: Check Javascript Vulnerabilities.
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        exit_code=0
        for file in ${{ inputs.files }}; do
          npx audit-ci --moderate $file || exit_code=1
        done
        exit $exit_code
    
