name: call advisor action
on: 
 push:
  branches: main
 
jobs:         
  call-advisor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
       fetch-depth: 0
    # - name: Define Files
    #   id: files
    #   run: echo "files=$(echo '["test-actions.yaml","go-releas.yaml"]')" >> $GITHUB_ENV
    - name: run composite workflow
      uses: saiteja-organization/test/.github/actions/advisor@main
      with: 
        files:  "js-lint.yml"
      #  github-token: ${{ GITHUB_TOKEN }}
