name: Create tag
on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Number of commits to fetch. 0 indicates all history for all branches and tags
        with:
          fetch-depth: 0
                   
      - name: Get latest tag
        run: |
             chmod +x $(pwd)/latest_tag.sh
             eval (/bin/bash $(pwd)/latest_tag.sh)
             echo "updated_version=$updated_version_tag" > $GITHUB_ENV

      - name: Release with latest tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: v${{ env.updated_version }}
          
