name: Create tag
on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Number of commits to fetch. 0 indicates all history for all branches and tags
                   
      - name: Get latest tag
        run: |
             chmod +x $(pwd)/latest_tag.sh
             /bin/bash $(pwd)/latest_tag.sh > updated_version_tag
             echo "updated_version=$(cat $(pwd)/updated_version_tag)" > $GITHUB_ENV
             
      - name: Create tag
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          tag: v${{ env.updated_version }}
          
