name: Create tag
on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # Number of commits to fetch. 0 indicates all history for all branches and tags
        with:
          fetch-depth: 0
                   
      - name: Get latest tag
        run: |
             chmod +x $(pwd)/latest_tag.sh
             /bin/bash $(pwd)/latest_tag.sh > updated_version_tag
             echo "updated_version=$(cat $(pwd)/updated_version_tag)" > $GITHUB_ENV
             
      - name: Create tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: v${{ env.updated_version }}
          
