name: Reusable workflow for jslint

on:
  workflow_call:
    inputs:
      workflow_id:
         required: true
         type: string
         description: "ID or filename of the workflow to get latest successful commit"
      files_to_match:
         description: "Check for changes using only this list of files or regex (Defaults to the entire repo)"
         required: true
         type: string
         default: (^|\/)yarn\.lock$
    secrets:
      gh_token:
         required:  true
      gh_repo_read_token:
         required:  true
jobs:
  changed_tf_files_job:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      # HACK: ideally this should be moved inside `github-actions/terraform-fmt`
      # but then post checkout action fails with no obvious way to fix it
      - uses: actions/checkout@v2
        with:
          # NOTE: we need to fetch commits for `push` trigger
          # as tj-actions/changed-files@v12 used by `test/javascript-lint` requires this
          fetch-depth: 0

      - name: Checkout actions repo
        uses: actions/checkout@v2
        with:
          repository: Tirumaladevib/test
          path: test
          ref: main
          token: ${{ secrets.GH_REPO_READ_TOKEN }}

      - name: Get changed tf files
        id: changed-files
        uses: ./github-actions/.github/actions/changed-files-since-last-success
        with:
          files_to_match: ${{ inputs.files_to_match }}
          github_token: ${{ secrets.GH_REPO_READ_TOKEN }}
          workflow_id: ${{ inputs.workflow_id }}
          
  audit_ci_frontend_job:
    runs-on: ubuntu-latest
    needs: changed_tf_files_job
    if: needs.changed_tf_files_job.outputs.any_changed == 'true'
    steps:
      - uses: actions/checkout@v2
        
      - name: Checkout actions repo
        uses: actions/checkout@v2
        with:
          repository: Tirumaladevib/test
          path: test
          ref: main
          token: ${{ secrets.GH_REPO_READ_TOKEN }}       

      - name: Get changed tf file for frontend
        if: always()
        id: check-javascript-lint1
        uses: ./github-actions/.github/actions/javascript-lint
        with:
          working_directory: app
          github_token: ${{ secrets.GH_REPO_READ_TOKEN }}
          
      - name: Get changed tf file for frontend
        if: always()
        id: check-javascript-lint2
        uses: ./github-actions/.github/actions/javascript-lint
        with:
          working_directory: server
          github_token: ${{ secrets.GH_REPO_READ_TOKEN }}
